# Settings for importing data and generating dataset.
#data import variables
DATASET_URL  = "https://github.com/uvicrepo/dataset-deadrepo/releases/download/v1.0/datasets.tar.gz"
DATASET_DIR = "data/raw"
FLOW_DIR = "flowFeatures_datasets"
PACKET_DIR = "packetFeatures_datasets"
PROCESSED_DATA_DIR = "data/processed"

#Data generation variables:
BENIGN_COUNT = 200000
ATTACK_MIN   = 4000
ATTACK_MAX   = 6200
MAX_SAMPLE_ROUNDS = 6

[FLOW_FILES]
"benign"=[
  "BenignTraffic.pcap_Flow.csv",
  "BenignTraffic1.pcap_Flow.csv",
  "BenignTraffic2.pcap_Flow.csv",
  "BenignTraffic3.pcap_Flow.csv"
]
"ddos_http"=["DDoS-HTTP_Flood-.pcap_Flow.csv"]
"dos_http"=[
  "DoS-HTTP_Flood.pcap_Flow.csv",
  "DoS-HTTP_Flood1.pcap_Flow.csv"
]
"dns_spoofing"=["DNS_Spoofing.pcap_Flow.csv"]
"xss"=["XSS.pcap_Flow.csv"]
"brute_force"=["DictionaryBruteForce.pcap_Flow.csv"]

[PACKET_FILES]
"benign"=[
  "BenignTraffic.csv",
  "BenignTraffic1.csv",
  "BenignTraffic2.csv",
  "BenignTraffic3.csv"
]
"ddos_http"=["DDoS-HTTP_Flood-.csv"]
"dos_http"=[
  "DoS-HTTP_Flood.csv",
  "DoS-HTTP_Flood1.csv"
]
"dns_spoofing"=["DNS_Spoofing.csv"]
"xss"=["XSS.csv"]
"brute_force"=["DictionaryBruteForce.csv"]

[ATTACK_KEYS]
  "ddos_http"="DDoS-HTTP Flood"
  "dos_http"="DoS-HTTP Flood"
  "dns_spoofing"="DNS Spoofing"
  "xss"="XSS"
  "brute_force"="Brute Force"

[EXPECTED_MATCH_RATE]
  "benign"=0.94
  "ddos_http"=0.99
  "dos_http"=0.99
  "dns_spoofing"=0.92
  "xss"=0.86
  "brute_force"=0.60