"""
check_categorical_features.py - audits every string/object column in
combined_sample.parquet and flow_training_sample.parquet, and writes a
markdown report recommending how to encode each one (or confirming it's
already excluded as an ID/label column).

Run once, after generate_dataset.py, from the scripts/ folder:
    python check_categorical_features.py

Produces: docs/categorical_feature_report.md
"""

import pandas as pd
from pathlib import Path
from dataImport import impsettings

REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR  = impsettings.PROCESSED_DATA_PATH
REPORT_PATH = REPO_ROOT / "docs" / "categorical_feature_report.md"

# Columns already identified as identifiers or labels (from earlier
# team discussion) -- these should NEVER be one-hot encoded as features,
# so they're reported separately rather than given an encoding recommendation.
KNOWN_ID_OR_LABEL_COLS = {
    "pkt_src_ip", "pkt_dst_ip", "pkt_src_port", "pkt_dst_port",
    "pkt_device_mac", "pkt_eth_src_oui", "pkt_eth_dst_oui", "pkt_stream",
    "flow_Flow ID", "flow_Src IP", "flow_Src Port", "flow_Dst IP",
    "flow_Dst Port", "flow_Timestamp",
    "pkt_label", "flow_Label", "flow_matched", "label",
}

# Thresholds for the encoding recommendation. These are starting points,
# not hard rules -- adjust based on what the team decides is an acceptable
# number of one-hot columns.
ONE_HOT_MAX_CARDINALITY = 15
FREQUENCY_ENCODING_MAX_CARDINALITY = 50


def _recommend(nunique: int, n_rows: int) -> str:
    if nunique == 1:
        return "Constant column -- only 1 distinct value across all rows. Provides no signal; consider dropping."
    if nunique == 2:
        return "Binary map (0/1) -- only 2 distinct values, no need for one-hot."
    if nunique <= ONE_HOT_MAX_CARDINALITY:
        return f"One-hot encode -- {nunique} categories is manageable ({nunique} new columns)."
    if nunique <= FREQUENCY_ENCODING_MAX_CARDINALITY:
        return (f"One-hot NOT recommended ({nunique} categories -> {nunique} new columns). "
                f"Consider frequency encoding or target encoding instead.")
    pct_unique = nunique / n_rows * 100
    return (f"HIGH CARDINALITY ({nunique} unique / {n_rows} rows = {pct_unique:.1f}%). "
            f"Likely an identifier that should be dropped, not encoded. "
            f"If genuinely a category (not an ID), use frequency/target encoding, never one-hot.")


def _audit_dataframe(df: pd.DataFrame, name: str) -> str:
    lines = [f"## {name}\n", f"Shape: {df.shape[0]:,} rows x {df.shape[1]} columns\n"]

    object_cols = list(df.select_dtypes(include=["object", "string"]).columns)
    if not object_cols:
        lines.append("No string/object columns found.\n")
        return "\n".join(lines)

    known = [c for c in object_cols if c in KNOWN_ID_OR_LABEL_COLS]
    unknown = [c for c in object_cols if c not in KNOWN_ID_OR_LABEL_COLS]

    if known:
        lines.append(f"**Already excluded (ID/label columns, not encoding candidates):** "
                      f"{', '.join(known)}\n")

    if not unknown:
        lines.append("No remaining string columns need an encoding decision.\n")
        return "\n".join(lines)

    lines.append("| Column | Unique values | Top value | Top value % | Recommendation |")
    lines.append("|---|---|---|---|---|")

    for col in unknown:
        nunique = df[col].nunique(dropna=True)
        vc = df[col].value_counts(dropna=True)
        top_val = vc.index[0] if len(vc) else "N/A"
        top_pct = (vc.iloc[0] / len(df) * 100) if len(vc) else 0
        rec = _recommend(nunique, len(df))
        # escape pipe characters in values so they don't break the markdown table
        top_val_str = str(top_val).replace("|", "\\|")[:40]
        lines.append(f"| `{col}` | {nunique:,} | `{top_val_str}` | {top_pct:.1f}% | {rec} |")

    lines.append("")
    return "\n".join(lines)


def main():
    combined_path = DATA_DIR / "combined_sample.parquet"
    flow_only_path = DATA_DIR / "flow_training_sample.parquet"

    report_sections = [
        "# Categorical Feature Encoding Audit\n",
        f"Generated by `check_categorical_features.py`. "
        f"Thresholds: one-hot up to {ONE_HOT_MAX_CARDINALITY} categories, "
        f"frequency/target encoding up to {FREQUENCY_ENCODING_MAX_CARDINALITY}, "
        f"anything higher is flagged as a likely identifier.\n",
    ]

    if combined_path.exists():
        wwt = pd.read_parquet(combined_path)
        report_sections.append(_audit_dataframe(wwt, "combined_sample.parquet (WWT)"))
    else:
        report_sections.append(f"## combined_sample.parquet\nFile not found at {combined_path}\n")

    if flow_only_path.exists():
        flow_only = pd.read_parquet(flow_only_path)
        report_sections.append(_audit_dataframe(flow_only, "flow_training_sample.parquet"))
    else:
        report_sections.append(f"## flow_training_sample.parquet\nFile not found at {flow_only_path}\n")

    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text("\n".join(report_sections))
    print(f"Report written to {REPORT_PATH}")


if __name__ == "__main__":
    main()